language: cpp
before_install:
  - sudo apt-get install python-software-properties software-properties-common
  - sudo add-apt-repository --yes ppa:team-xbmc/unstable
  - sudo add-apt-repository --yes ppa:team-xbmc/xbmc-ppa-build-depends
  - sudo apt-get update
  - sudo apt-get build-dep xbmc
script:
  - ./bootstrap
  - ./configure
  - make -j12
branches:
  only:
    - master
os:
  - linux
notifications:
  slack: pixl-project:KZntwF8twUVO3oFMbevQuOur
